services:
  catalogDb:
    image: postgres
    container_name: catalogDb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
        - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d CatalogDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  basketDb:
    image: postgres
    container_name: basketDb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5434:5432"
    volumes:
        - basket_postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d BasketDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  redis:
    container_name: RedisDistributedCache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  
  orderingDb:
    image: postgres
    container_name: orderingDb
    environment:
      - POSTGRES_USER=${ORDER_USER}
      - POSTGRES_PASSWORD=${ORDER_PASSWORD}
      - POSTGRES_DB=OrderingDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
        - ordering_postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_USER} -d OrderingDb"]
      interval: 10s
      timeout: 5s
      retries: 5
  authDb:
    image: postgres
    container_name: authDb
    environment:
      - POSTGRES_USER=${AUTH_USERNAME_DB}
      - POSTGRES_PASSWORD=${AUTH_PASSWORD_DB}
      - POSTGRES_DB=AuthDb
    restart: always
    ports:
        - "5440:5432"
    volumes:
        - auth_postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_USERNAME_DB} -d AuthDb"]
      interval: 10s
      timeout: 5s
      retries: 5
  #--------------------------------------------------------------------------------------------------------------------
  seq:
    container_name: seq
    environment: 
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True 
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"


  messagebus :
    image: rabbitmq:management
    container_name: travelticket-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    
  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: paperCut
    ports:
      - "8080:8080"
      - "2525:2525"
    restart: unless-stopped

#-----------------------------------------------------------------------------------------------------------
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=CatalogDb;Port=5432;Database=OrderingDb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - MessageBroker__Host=amqp://messagebus:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6000:8080" 
    depends_on:
      catalogDb:
        condition: service_healthy
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgresDefaultConnection=Host=orderingDb;Port=5432;Database=OrderingDb;Username=${ORDER_USER};Password=${ORDER_PASSWORD};
      - MessageBroker__Host=amqp://messagebus:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6080:8080"
    depends_on:
      orderingDb:
        condition: service_healthy
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=authDb;Port=5432;Database=AuthDb;Username=${AUTH_USERNAME_DB};Password=${AUTH_PASSWORD_DB};
    ports:
      - "6066:8080"
    depends_on:
       authDb :
        condition: service_healthy
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=basketDb;Port=5432;Database=BasketDb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ConnectionStrings__Redis=redis:6379 
      - MessageBroker__Host=amqp://messagebus:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6003:8080"
    depends_on:
      basketDb :
        condition: service_healthy
      redis:
        condition: service_healthy
      messagebus:
        condition: service_healthy
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
