services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogDb:
    image: postgres
  basketDb:
    image: postgres

volumes:
  postgres_data:
  basket_postgres:
