services:
  catalogDb:
    image: postgres

  basketDb:
    image: postgres

  orderingDb:
    image: postgres

  authDb:
    image: postgres
  redis:
    image: redis

  messagebus:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  seq:
    image: datalust/seq:latest

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
  # basket.api:
  #   image: basketapi
  #   build:
  #     context: .
  #     dockerfile: Services/Basket/Basket.API/Dockerfile

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: Services/Auth/AuthService/Dockerfile

volumes:
  postgres_data:
  basket_postgres:
  ordering_postgres:
  auth_postgres:
  rabbitmq_data:

