services:
  catalogDb:
    image: postgres

  basketDb:
    image: postgres

  orderingDb:
    image: postgres

  redis:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  seq:
    image: datalust/seq:latest

  # basket.api:
  #   image: basketapi
  #   build:
  #     context: .
  #     dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_data:
  basket_postgres:
  ordering_postgres:
